project:
  type: website

website:
  title: "Practical Assignments"
  navbar:
    left:
      - text: "Prac 1"
        href: prac1.qmd
      - text: "Day 3 Prac"
        href: day3_prac4_5.qmd
      - text: "Prac 4"
        href: prac4.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual
